#!/usr/bin/env bash
#Crack MD5 Hash

clear #Clearing the terminal
echo -e "MD5 Hash Cracker\n"  #ADD AN ASCII ART HERE

cleanup2 () {
  rm $PWD/.temp/.opt* &> /dev/null
  rm $PWD/.temp/.temp* &> /dev/null
}

trap_ctrlc () {
    echo -e "\nCtrl-C caught...Performing Clean Up Thanks for Using."
    cleanup2
    exit 2
}

trap "trap_ctrlc" 2

read_md5 () {

  read -p $'\e[1;91mEnter the MD5 Hash here\e[0m\e[24;1;97m : ' md5_1hash
  md5_1hash_lenght=${#md5_1hash}
}

hash_length () {

  if [ "$md5_1hash_lenght" != "32" ]
   then
       echo -e "The provided Hash is not an MD5 Hash, the MD5 hash string contains 32 digit."
       read_md5
       hash_length
  fi
}

wordlist_md5 () {

  read -p $'\e[1;91mEnter the path of the wordlist or press Enter for default wordlist\e[0m\e[24;1;97m : ' password2_list
  if [ "$password2_list" = "" ]
    then
         password2_list=$PWD/wordlist.txt
         echo -e "\n\nUsing the default wordlist, Fingers Crossed"
    else
         if [ -f $password2_list ]
           then
               echo -e "\n\nUsing the provided wordlist, Fingers Crossed, Wait it can take a while depending on the wordlist :::\n\n"
           else
               echo -e "The provided file does not exist please provide another wordlist file"
               wordlist_md5
         fi
  fi

}

cracking_md5 () {

echo "$md5_1hash" > $PWD/.temp/.temp_md5hash
wordlist_md5
time=$(date +"%T")
mv ~/.john/john.pot $PWD/.john.pot/$time-john.pot.bk
john --format=Raw-MD5 $PWD/.temp/.temp_md5hash -w=$password2_list &> $PWD/.temp/.opt3
crack_pass2=$(awk '/?/ {print $1}' $PWD/.temp/.opt3)

if [ "$crack_pass2" = "" ]
   then
      echo -e "Sorry the password was not cracked try another wordlist."
      exit
   else
      echo -e "Congratulations the password is cracked and the password is $crack_pass2"
      echo -e "\nMD5 Hash                                         Password\n$md5_1hash        =        $crack_pass2" >> cracked_password.txt
fi


}

read_md5
hash_length
cracking_md5
cleanup2
