#!/usr/bin/env bash

#Crack Linux USER and Root Password

clear #Clearing the terminal
echo -e "HASH password cracker\n"  #ADD AN ASCII ART HERE

cleanup1 () {
  rm $PWD/.temp/.opt* &> /dev/null
}

trap_ctrlc () {
    echo -e "\nCtrl-C caught...Performing Clean Up Thanks for Using."
    cleanup1
    exit 2
}

trap "trap_ctrlc" 2

options-list2 () {

echo -e "\e[1;93m1.   \e[1;92mAutomatically crack the system's Root password"
echo -e "\e[1;93m2.   \e[1;92mCrack the defined USER password"
echo -e "\e[1;93m3.   \e[1;92mProvide the 'shadow' file path\n\n"

}

options-selector2 () {

while true;
do
read -p $'\e[1;4;91mSELECT ONE OF THE OPTIONS WITH THE RESPECTED NUMBER\e[0m\e[24;1;97m : ' options4
case $options4 in
[1]* )  opt1-1 ;exit;;
[2]* )  opt1-2 ;exit;;
[3]* )  opt1-3 ;exit;;
* ) clear && options-list2 && echo -e "\e[1;92mPlease answer it with right options \n\e[0m";;
esac
done

}
