#!/usr/bin/env bash
#Crack SHA1 Hash

clear #Clearing the terminal
echo -e "SHA1 Hash Cracker\n"  #ADD AN ASCII ART HERE

cleanup () {
  rm $PWD/.temp/.opt* &> /dev/null
  rm $PWD/.temp/.temp* &> /dev/null
}

trap_ctrlc () {
    echo -e "\n\nCtrl-C caught...Performing Clean Up Thanks for Using.\n"
    cleanup
    exit 2
}

trap "trap_ctrlc" 2

read_sha1 () {

  read -p $'\e[1;91mEnter the SHA1 Hash here\e[0m\e[24;1;97m : ' sha1_1hash
  sha1_1hash_lenght=${#sha1_1hash}
}

hash_length () {

  if [ "$sha1_1hash_lenght" != "40" ]
   then
       echo -e "\nThe provided Hash is not an SHA1 Hash, the SHA1 hash string contains 40 character.\n"
       read_sha1
       hash_length
  fi
}

wordlist_sha1 () {

  read -p $'\e[1;91m\nEnter the path of the wordlist or press Enter for default wordlist\e[0m\e[24;1;97m : ' password2_list
  if [ "$password2_list" = "" ]
    then
         password2_list=$PWD/wordlist.txt
         echo -e "\n\nUsing the default wordlist, Fingers Crossed"
    else
         if [ -f $password2_list ]
           then
               echo -e "\n\nUsing the provided wordlist, Fingers Crossed, Wait it can take a while depending on the wordlist :::\n\n"
           else
               echo -e "The provided file does not exist please provide another wordlist file"
               wordlist_sha1
         fi
  fi

}

cracking_sha1 () {

echo "$sha1_1hash" > $PWD/.temp/.temp_sha1hash
wordlist_sha1
time=$(date +"%T")
mv ~/.john/john.pot $PWD/.john.pot/$time-john.pot.bk &> /dev/null
john --format=Raw-sha1 $PWD/.temp/.temp_sha1hash -w=$password2_list &> $PWD/.temp/.opt3
crack_pass2=$(awk '/?/ {print $1}' $PWD/.temp/.opt3)

if [ "$crack_pass2" = "" ]
   then
      echo -e "Sorry the password was not cracked try another wordlist."
      exit
   else
      echo -e "\nCongratulations the password is cracked and the password is $crack_pass2"
      echo -e "\nSHA1 Hash                                         Password\n$sha1_1hash        =        $crack_pass2" >> cracked_password.txt
fi


}

read_sha1
hash_length
cracking_sha1
cleanup
